# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-19 15:12
from __future__ import unicode_literals

import aldryn_apphooks_config.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingconfig',
            options={'verbose_name': 'Booking object', 'verbose_name_plural': 'Booking objects'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='app_config',
            field=aldryn_apphooks_config.fields.AppHookConfigField(default=None, help_text='When selecting a value, the form is reloaded to get the updated default', on_delete=django.db.models.deletion.CASCADE, to='booking_app.BookingConfig', verbose_name='Booking object'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingconfig',
            unique_together=set([]),
        ),
    ]
