# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent_calendar', '0002_auto_20171119_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventcalenderday',
            name='day',
            field=models.DateField(verbose_name='date'),
        ),
    ]
