# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-17 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
        migrations.AddField(
            model_name='profile',
            name='start_year',
            field=models.IntegerField(default=0, verbose_name='Start_year'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, choices=[(b'M', 'Mechanical engingering'), (b'DPU', 'Design and Product Development'), (b'EMM', 'Energy-Environment-Management'), (b'Master', 'Masterprogram'), (b'Other', 'Other')], max_length=10, verbose_name='Program'),
        ),
    ]
