# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0004_auto_20171027_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, choices=[(b'M', 'Mechanical engingering'), (b'DPU', 'Design and Product Development'), (b'EMM', 'Energy-Environment-Management'), (b'MASTER', 'Masterprogram'), (b'EX', 'Exchange student'), (b'OTHER', 'Other')], max_length=10, verbose_name='Program'),
        ),
    ]
