# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-29 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0007_auto_20171029_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Sign up', 'verbose_name_plural': 'Sign ups'},
        ),
    ]
