# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-29 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0008_auto_20171029_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Sign up', 'verbose_name_plural': 'Sign ups'},
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together=set([('user', 'event')]),
        ),
    ]
