# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-14 22:37
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('maskin', '0009_auto_20171030_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=b'placeholder_name', to='cms.Placeholder'),
        ),
    ]
