# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-31 21:20
from __future__ import unicode_literals

import aldryn_categories.fields
import aldryn_newsblog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('aldryn_categories', '0004_auto_20150623_0859'),
        ('aldryn_newsblog', '0015_auto_20161208_0403'),
        ('maskin', '0011_remove_event_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlogLatestArticleByCategory',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('latest_articles', models.IntegerField(default=5, help_text='The maximum number of latest articles to display.')),
                ('app_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aldryn_newsblog.NewsBlogConfig', verbose_name='Apphook configuration')),
                ('categories', aldryn_categories.fields.CategoryManyToManyField(blank=True, to='aldryn_categories.Category', verbose_name='categories')),
            ],
            options={
                'abstract': False,
            },
            bases=(aldryn_newsblog.models.PluginEditModeMixin, 'cms.cmsplugin'),
        ),
    ]
