# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0011_remove_event_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Sign up', 'verbose_name_plural': 'Sign ups'},
        ),
        migrations.RemoveField(
            model_name='signup',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='signup',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AddField(
            model_name='signup',
            name='checkin',
            field=models.BooleanField(default=False, verbose_name='check-in'),
        ),
        migrations.AddField(
            model_name='signup',
            name='signup',
            field=models.BooleanField(default=False, verbose_name='signup'),
        ),
        migrations.AddField(
            model_name='signup',
            name='timestamp_checkin',
            field=models.DateTimeField(default=datetime.datetime(998, 12, 31, 23, 0, tzinfo=utc), verbose_name='timestamp check-in'),
        ),
        migrations.AddField(
            model_name='signup',
            name='timestamp_signup',
            field=models.DateTimeField(default=datetime.datetime(998, 12, 31, 23, 0, tzinfo=utc), verbose_name='timestamp signup'),
        ),
    ]
