# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-02 18:45
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('maskin', '0012_auto_20180201_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=b'Info', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'No signup'), (1, 'Max limit'), (2, 'Selection')], default=0, verbose_name='Type'),
        ),
    ]
