# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0013_memberpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rfid',
            field=models.IntegerField(default=0, verbose_name='LiUID Card number'),
        ),
    ]
