# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0013_auto_20180202_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maxsignups',
            field=models.IntegerField(default=9999, verbose_name='Max signups'),
        ),
    ]
