# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-30 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskin', '0014_profile_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rfid',
            field=models.BigIntegerField(default=0, verbose_name='LiUID Card number'),
        ),
    ]
